# Generated by Django 5.2.15 on 2026-06-22 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GAMEDEX', '0007_rename_creada_comunidad_creado_comunidad_modificado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='direccion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
