# Generated by Django 5.2.15 on 2026-06-23 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GAMEDEX', '0008_perfil_direccion_perfil_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='perfil',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
